#!/usr/bin/env python3
"""Regenerates main/ui_icons/*.c from tools/icon_src/*.png.

Same reasoning as convert_logos.py (see its own docstring) - these are
the remaining PNGs that were still runtime-decoded from the SPIFFS
`storage` partition: the weather condition icon, wind/humidity icons,
the sun/arrow icons, and the Claude/Spotify header logos. The weather
condition icon and the sun/arrow icons are re-decoded every 3 seconds
forever (update_sun_event_label() runs on home_screen.c's own timer
tick), not just per-update like the airline logos were - an even
tighter, more frequent hit against the same decode-needs-a-contiguous-
heap-allocation problem. Live-caught 2026-09-17: the weather condition
icon, wind icon, humidity icon, and sun icon all went blank at once
while their text values kept updating fine - same signature as the
airline logo bug, just here instead.

Run this after replacing/adding a file in tools/icon_src/. Requires
`pip install --user --break-system-packages pypng lz4` once (already
done on this Mac - see convert_logos.py).
"""
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC_DIR = ROOT / "tools" / "icon_src"
OUT_DIR = ROOT / "main" / "ui_icons"
LVGL_IMAGE_PY = ROOT / "managed_components" / "lvgl__lvgl" / "scripts" / "LVGLImage.py"
CMAKE_FILE = ROOT / "main" / "CMakeLists.txt"

COLOR_FORMAT = "RGB565A8"  # see convert_logos.py for why


def main():
    pngs = sorted(SRC_DIR.glob("*.png"))
    if not pngs:
        print(f"No PNGs found in {SRC_DIR}", file=sys.stderr)
        sys.exit(1)

    names = []
    for png in pngs:
        name = png.stem
        names.append(name)
        subprocess.run(
            [
                sys.executable,
                str(LVGL_IMAGE_PY),
                str(png),
                "--ofmt", "C",
                "--cf", COLOR_FORMAT,
                "--name", name,
                "-o", str(OUT_DIR),
            ],
            check=True,
        )

        out_file = OUT_DIR / f"{name}.c"
        text = out_file.read_text()
        text = re.sub(
            r"#if defined\(LV_LVGL_H_INCLUDE_SIMPLE\).*?#endif\n",
            '#include "lvgl.h"\n',
            text,
            count=1,
            flags=re.DOTALL,
        )
        out_file.write_text(text)

    header_lines = [
        "/* Generated by tools/convert_ui_icons.py - do not hand-edit.",
        " * Regenerate after adding/changing a file in tools/icon_src/. */",
        "#pragma once",
        "",
        '#include "lvgl.h"',
        "",
    ]
    for name in names:
        header_lines.append(f"extern const lv_image_dsc_t {name};")
    header_lines.append("")
    (OUT_DIR / "ui_icons.h").write_text("\n".join(header_lines))

    cmake_text = CMAKE_FILE.read_text()
    generated_srcs = "\n".join(f'        "ui_icons/{name}.c"' for name in names)
    marker_start = "        # BEGIN generated ui icons - see tools/convert_ui_icons.py\n"
    marker_end = "        # END generated ui icons\n"
    block = marker_start + generated_srcs + "\n" + marker_end
    if marker_start in cmake_text:
        cmake_text = re.sub(
            re.escape(marker_start) + r".*?" + re.escape(marker_end),
            block,
            cmake_text,
            flags=re.DOTALL,
        )
    else:
        cmake_text = cmake_text.replace(
            "        # END generated airline logos\n",
            "        # END generated airline logos\n" + block,
        )
    CMAKE_FILE.write_text(cmake_text)

    print(f"Converted {len(names)} icons into {OUT_DIR}, updated CMakeLists.txt")


if __name__ == "__main__":
    main()
