#!/usr/bin/env python3
"""Regenerates main/airline_logos/*.c from tools/logo_src/*.png.

Run this after fetch_logos.py adds/replaces a logo, or after hand-editing
a PNG in logo_src/. Requires `pip install --user pypng lz4` once (LVGLImage.py's
own dependencies).

Why this exists at all (2026-09-17): airline logos used to live as PNGs in
the SPIFFS `storage` partition, decoded at runtime by LVGL every time a
logo needed to show. That partition was already nearly full (500KB/512KB),
and worse, the runtime decode needs a real contiguous heap allocation on a
device that runs at ~8.5KB free internal heap - a transient allocation
failure at the wrong moment silently produces a blank/missing logo with no
error (three separate real incidents caught live: American Airlines,
Delta, UPS - all different images, same root cause). Pre-decoding at build
time into a compiled-in raw array removes the runtime decode step (and
its heap dependency) entirely - displaying a logo becomes "point at this
data already sitting in flash," the same as any other compiled constant.
"""
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC_DIR = ROOT / "tools" / "logo_src"
OUT_DIR = ROOT / "main" / "airline_logos"
LVGL_IMAGE_PY = ROOT / "managed_components" / "lvgl__lvgl" / "scripts" / "LVGLImage.py"
CMAKE_FILE = ROOT / "main" / "CMakeLists.txt"

# RGB565A8 = native 16-bit color (matches this build's CONFIG_LV_COLOR_DEPTH=16,
# no runtime color conversion) + a full 8-bit alpha plane (needed for the
# transparent-background logos that get a white contrast chip behind them -
# see logo_needs_white_bg() in home_screen.c). Half the size of ARGB8888
# for the same alpha fidelity.
COLOR_FORMAT = "RGB565A8"


def main():
    pngs = sorted(SRC_DIR.glob("*.png"))
    if not pngs:
        print(f"No PNGs found in {SRC_DIR}", file=sys.stderr)
        sys.exit(1)

    codes = []
    for png in pngs:
        code = png.stem
        if not re.fullmatch(r"[a-z]{3}", code):
            print(f"skipping {png.name} - not a 3-letter airline code", file=sys.stderr)
            continue
        codes.append(code)
        subprocess.run(
            [
                sys.executable,
                str(LVGL_IMAGE_PY),
                str(png),
                "--ofmt", "C",
                "--cf", COLOR_FORMAT,
                "--name", code,
                "-o", str(OUT_DIR),
            ],
            check=True,
        )

        # LVGLImage.py's own conditional include block guesses at how the
        # including project reaches lvgl.h (LV_LVGL_H_INCLUDE_SIMPLE/
        # _SYSTEM/LV_BUILD_TEST) - none of those are defined in this
        # project's build, so it always fell through to "lvgl/lvgl.h",
        # which doesn't exist here (this project reaches it as a plain
        # "lvgl.h", same as the vendored component's own CMakeLists
        # exposes it). Swap in the one #include this project actually
        # needs instead of guessing.
        out_file = OUT_DIR / f"{code}.c"
        text = out_file.read_text()
        text = re.sub(
            r"#if defined\(LV_LVGL_H_INCLUDE_SIMPLE\).*?#endif\n",
            '#include "lvgl.h"\n',
            text,
            count=1,
            flags=re.DOTALL,
        )
        out_file.write_text(text)

    # Each code now has its own .c file (from LVGLImage.py) - write the
    # single generated index file that ties them all together.
    index_lines = [
        "/* Generated by tools/convert_logos.py - do not hand-edit.",
        " * Regenerate after adding/changing a file in tools/logo_src/. */",
        "",
        '#include "airline_logos.h"',
        "",
        "#include <string.h>",
        "",
    ]
    for code in codes:
        index_lines.append(f"extern const lv_image_dsc_t {code};")
    index_lines.append("")
    index_lines.append("typedef struct {")
    index_lines.append("    const char *code;")
    index_lines.append("    const lv_image_dsc_t *dsc;")
    index_lines.append("} airline_logo_entry_t;")
    index_lines.append("")
    index_lines.append("static const airline_logo_entry_t AIRLINE_LOGOS[] = {")
    for code in codes:
        index_lines.append(f'    {{"{code}", &{code}}},')
    index_lines.append("};")
    index_lines.append("")
    index_lines.append("const lv_image_dsc_t *airline_logo_lookup(const char *code)")
    index_lines.append("{")
    index_lines.append("    for (size_t i = 0; i < sizeof(AIRLINE_LOGOS) / sizeof(AIRLINE_LOGOS[0]); i++) {")
    index_lines.append("        if (strcmp(code, AIRLINE_LOGOS[i].code) == 0) {")
    index_lines.append("            return AIRLINE_LOGOS[i].dsc;")
    index_lines.append("        }")
    index_lines.append("    }")
    index_lines.append("    return NULL;")
    index_lines.append("}")
    index_lines.append("")
    (OUT_DIR / "airline_logos_index.c").write_text("\n".join(index_lines))

    # Rewrite CMakeLists.txt's SRCS list to include every generated file -
    # idf_component_register() here uses an explicit list, not a glob.
    cmake_text = CMAKE_FILE.read_text()
    generated_srcs = "\n".join(
        f'        "airline_logos/{code}.c"' for code in codes
    )
    generated_srcs += '\n        "airline_logos/airline_logos_index.c"'
    marker_start = "        # BEGIN generated airline logos - see tools/convert_logos.py\n"
    marker_end = "        # END generated airline logos\n"
    block = marker_start + generated_srcs + "\n" + marker_end
    if marker_start in cmake_text:
        cmake_text = re.sub(
            re.escape(marker_start) + r".*?" + re.escape(marker_end),
            block,
            cmake_text,
            flags=re.DOTALL,
        )
    else:
        cmake_text = cmake_text.replace(
            '        "fonts/lv_font_montserrat_18_latin_ext_bold.c"\n',
            '        "fonts/lv_font_montserrat_18_latin_ext_bold.c"\n' + block,
        )
    CMAKE_FILE.write_text(cmake_text)

    print(f"Converted {len(codes)} logos into {OUT_DIR}, updated CMakeLists.txt")


if __name__ == "__main__":
    main()
