/* Generated by tools/convert_ui_icons.py - do not hand-edit.
 * Regenerate after adding/changing a file in tools/icon_src/. */
#pragma once

#include "lvgl.h"

extern const lv_image_dsc_t arrow_down;
extern const lv_image_dsc_t arrow_up;
extern const lv_image_dsc_t claude_logo;
extern const lv_image_dsc_t f1_car;
extern const lv_image_dsc_t f1_flag;
extern const lv_image_dsc_t f1_watch;
extern const lv_image_dsc_t flag_cop;
extern const lv_image_dsc_t flag_eur;
extern const lv_image_dsc_t flag_gbp;
extern const lv_image_dsc_t icon_euro;
extern const lv_image_dsc_t icon_gbp;
extern const lv_image_dsc_t icon_humidity;
extern const lv_image_dsc_t icon_wind;
extern const lv_image_dsc_t nws_hurricane;
extern const lv_image_dsc_t nws_warning;
extern const lv_image_dsc_t spotify_logo;
extern const lv_image_dsc_t sun_icon;
extern const lv_image_dsc_t wx_cloudy;
extern const lv_image_dsc_t wx_fog;
extern const lv_image_dsc_t wx_moon;
extern const lv_image_dsc_t wx_moon_rain;
extern const lv_image_dsc_t wx_mostly_cloudy;
extern const lv_image_dsc_t wx_mostly_cloudy_night;
extern const lv_image_dsc_t wx_partly;
extern const lv_image_dsc_t wx_partly_night;
extern const lv_image_dsc_t wx_rain;
extern const lv_image_dsc_t wx_rain_heavy;
extern const lv_image_dsc_t wx_rain_light;
extern const lv_image_dsc_t wx_snow;
extern const lv_image_dsc_t wx_sun;
extern const lv_image_dsc_t wx_sun_rain;
extern const lv_image_dsc_t wx_thunder;
